#!/system/xbin/bash

. /system/etc/pdsshd.conf

if [ -e $PID ]; then
kill -9 $(cat $PID)
rm $PID
fi

/system/exbin/dropbear -A -N root -U 0 -G 0 -T /etc/.ssh/authorized_keys/id_rsa.pub -C "$PASS" -p "$PORT" -P $PID

echo "Check if Dropbear is running..."

echo ""

ps | grep dropbear

echo "" 

echo "done"

exit 0

