#!/system/bin/sh

. /system/etc/pdsshd.conf

if [ test $CONFIGURED -eq 0 ]; then
mount -o remount,rw /system
sleep 1
cp -R /data/etc/ /system/
sleep 1
mount -o remount,ro /system
fi

sleep 1

pdsshd-toolkit -e &
